# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_window = QtWidgets.QFrame(self.centralwidget)
        self.main_window.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_window.setObjectName("main_window")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_window)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3.addWidget(self.main_window)
        self.tree_view = TreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_view.sizePolicy().hasHeightForWidth())
        self.tree_view.setSizePolicy(sizePolicy)
        self.tree_view.setObjectName("tree_view")
        self.horizontalLayout_3.addWidget(self.tree_view)
        self.edit_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_panel.sizePolicy().hasHeightForWidth())
        self.edit_panel.setSizePolicy(sizePolicy)
        self.edit_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.edit_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.edit_panel.setLineWidth(0)
        self.edit_panel.setObjectName("edit_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.edit_panel)
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools = QtWidgets.QFrame(self.edit_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools.sizePolicy().hasHeightForWidth())
        self.tools.setSizePolicy(sizePolicy)
        self.tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tools.setLineWidth(0)
        self.tools.setObjectName("tools")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tools)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.transducers = QtWidgets.QComboBox(self.tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transducers.sizePolicy().hasHeightForWidth())
        self.transducers.setSizePolicy(sizePolicy)
        self.transducers.setMinimumSize(QtCore.QSize(0, 0))
        self.transducers.setObjectName("transducers")
        self.horizontalLayout_2.addWidget(self.transducers)
        self.clear = QtWidgets.QPushButton(self.tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setObjectName("clear")
        self.horizontalLayout_2.addWidget(self.clear)
        self.from_clip = QtWidgets.QPushButton(self.tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_clip.sizePolicy().hasHeightForWidth())
        self.from_clip.setSizePolicy(sizePolicy)
        self.from_clip.setObjectName("from_clip")
        self.horizontalLayout_2.addWidget(self.from_clip)
        self.verticalLayout.addWidget(self.tools)
        self.tree_repr = ValidateText(self.edit_panel)
        self.tree_repr.setTabStopWidth(30)
        self.tree_repr.setObjectName("tree_repr")
        self.verticalLayout.addWidget(self.tree_repr)
        self.horizontalLayout_3.addWidget(self.edit_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tree GUI"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.from_clip.setText(_translate("MainWindow", "I"))

from ui.validate_text import ValidateText
from ui.view import TreeView
